### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by MarioOcampo** [ejcanalesr/parametric-T2-spiral#1]
Hello Erick,
I hope you are doing well.

We tried to use the function `call_estimation_script.py` and we had the error 

`AttributeError: module 'progressbar' has no attribute 'progressbar'`

We solved it installing `progressbar2`. 

I'm creating the issue in case someone else has this error. 

Best regards
Mario

**Comment by ejcanalesr** [comment]
I updated the list of dependencies: progressbar -> progressbar2
Thanks!
Erick

**Comment by ejcanalesr** [comment]
Hi Mario,

Glad to hear from you!


This library is in the list of dependencies.

I should update the name, progressbar -> progressbar2

Thanks!

All the best,

Erick






________________________________
From: Mario Ocampo ***@***.***>
Sent: Friday, May 27, 2022 2:44 PM
To: ejcanalesr/parametric-T2-spiral
Cc: Subscribed
Subject: [ejcanalesr/parametric-T2-spiral] Update dependency (Issue #1)


Hello Erick,
I hope you are doing well.

We tried to use the function call_estimation_script.py and we had the error

AttributeError: module 'progressbar' has no attribute 'progressbar'

We solved it installing progressbar2.

I'm creating the issue in case someone else has this error.

Best regards
Mario
